#spring配置
spring:
  #数据库连接池
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/carbon?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 13579MXZmxz...
    druid:
      initial-size: 5 # 初始化大小，最小，最大
      min-idle: 5
      max-active: 200
      max-wait: 120000 # 配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 28000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true # 打开PSCache，并且指定每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      use-global-data-source-stat: true
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录

  #redis配置
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 5000ms
      jedis:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0

  #nacos 服务注册与发现
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848


