#spring配置
spring:
  #数据库连接池
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/carbon?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 13579MXZmxz...
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 200
      max-wait: 120000
      time-between-eviction-runs-millis: 28000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  #redis
  redis:
    host: 127.0.0.1
    port: 6379
  #nacos 服务注册与发现
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848

# 设置 feign 超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

# 消息队列（如果不需要，可以注释掉）
#rocketmq:
#  name-server: 127.0.0.1:9876
#  producer:
#    group: carbon-assets
#    send-message-timeout: 300000

